config/routes.rb
Rails.application.routes.draw do
  #devise_scope :user do
  #  get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  #  get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  #end
  devise_for :users
  resources :camp_types
  resources :camp_infos
  resources :amenities
  resources :site_setups
  resources :images
  resources :contacts
  resources :addresses
  resources :camps do
    collection do
      get 'search'
      get 'all'
      get 'site_index'
    end
    member do
      put 'update_value'
    end
  end

  get '*path' => redirect('/')

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

  # The priority is based on order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'camps#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/camp.rb
class Camp < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged]
  validates :name, presence: true

  has_one :address, :dependent => :destroy
  belongs_to :contact
  has_one :site_setup
  has_many :images, :dependent => :destroy
  has_one :camp_info

  accepts_nested_attributes_for :images, :site_setup, :address, :camp_info
end

app/models/camp_type.rb
class CampType < ActiveRecord::Base
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  #before_action :authenticate_user!, only: [:index, :edit, :update, :destroy]
  before_action :states_var
  before_action :set_camp, only: [:show, :edit, :update, :destroy, :update_value]
  before_action :fix_state, only: [:search]


  # GET /camps
  # GET /camps.json
  def search
    if params[:city] == ''
      search_by_state
    else
      search_by_address
    end

    @camps.select!{|c| c.site_setup.hotel >= params[:hotel].to_i &&  c.site_setup.group_local_bath >= params[:group_local_bath].to_i &&  c.site_setup.group_sep_bath >= params[:group_sep_bath].to_i &&  c.site_setup.rustic >= params[:rustic].to_i &&  c.site_setup.rv >= params[:rv].to_i}
    @camps.select!{|c| c.bar}

    @farther_camps.select!{|c| c.bar}

    @hash = Gmaps4rails.build_markers(@all_addresses) do |address, marker|
      marker.lat address.lat
      marker.lng address.lon
      marker.json({ id: address.id})
      camp = address.camp
      marker.infowindow "<a href='/camps/#{camp.id}' class='infowindow-link'>#{camp.name}<br/>#{address.city}, #{address.state}</a>"
    end

    if @hash.empty?
      latlon = Geocoder.coordinates(params[:state])
      temp = {lat: latlon[0], lng: latlon[1], id: 0, :infowindow => "No Camps Found in the Area"}
      @hash << temp
    end
  end

  def search_by_state
    #if the search param is a full state name
    if @states.select{|state, abv| state.upcase == params[:state].upcase}
      state = @states.select{|state, abv| abv.upcase == params[:state].upcase}
      full_state = state.empty? ? params[:state] : state[0][0]
      addresses = Address.where(state: params[:state])
      @camps = addresses.map{|a| a.camp}.sort_by{|c| addresses.map(&:id)}
      farther_addresses = Address.near(full_state, 300).order("distance")

      farther_addresses.uniq

      @farther_camps = farther_addresses.map{|a| a.camp}.sort_by{|c| farther_addresses.map(&:id)} - @camps

      @all_addresses = addresses + farther_addresses
    elsif @states.select{|state, abv| abv.upcase == params[:state].upcase}
      state = @states.select{|state, abv| abv.upcase == params[:state].upcase}

      addresses = Address.where(state: state.upcase)
      @camps = addresses.map{|a| a.camp}.sort_by{|c| addresses.map(&:id)}

      farther_addresses = Address.near(params[:state], 300).order("distance")

      farther_addresses.uniq

      @farther_camps = farther_addresses.map{|a| a.camp}.sort_by{|c| farther_addresses.map(&:id)} - @camps

      @all_addresses = addresses + farther_addresses
    else
      search_by_address
    end
  end

  def search_by_address
    search = params[:city] + ", " + params[:state]
    addresses = Address.near(search, 150).order("distance")
    @camps = addresses.map{|a| a.camp}.sort_by{|c| addresses.map(&:id)}

    farther_addresses = Address.near(search, 300).order("distance")

    #find camps in the same state. But problem is with "El Paso, Tx"
    words = search.split(/\W+/)
    words.each do |word|
      state = @states.select{|state, abv| state.upcase == word.upcase}
      word = state.empty? ? word : state[0][1]

      Address.where(state: word.upcase).each do |address|
        farther_addresses << address
      end
    end

    farther_addresses.uniq

    @farther_camps = farther_addresses.map{|a| a.camp}.sort_by{|c| farther_addresses.map(&:id)} - @camps

    @all_addresses = addresses + farther_addresses
  end

  # GET /camps/1
  # GET /camps/1.json
  def show
  end

  def index
    @camps = Camp.all.order(:name)
  end

  def all
    @camps = Camp.all.order(:name)
  end

  # GET /camps/new
  def new
    @camp = Camp.new
    @camp.build_address
    @camp.build_site_setup
    @camp.build_camp_info
    3.times {@camp.images.build}
  end

  # GET /camps/1/edit
  def edit
    3.times {@camp.images.build} if @camp.images.blank?
    @camp.build_camp_info if @camp.camp_info.nil?
  end

  # POST /camps
  # POST /camps.json
  def create
    @camp = Camp.new(camp_params)

    respond_to do |format|
      if @camp.save
        format.html { redirect_to @camp, notice: 'Camp was successfully created.' }
        format.json { render :show, status: :created, location: @camp }
      else
        format.html { render :new }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /camps/1
  # PATCH/PUT /camps/1.json
  def update
    user = User.find_by_email @camp.contact.try(:email)
    if user.nil?
      contact = Contact.create(f_name:"Camp", l_name:"Contact",email:params[:email])
      @camp.update_column("contact_id", contact.id)
      User.create(email:params[:email], password:"pccca_2017")
    else
      user.update_column("email",params[:email])
      @camp.contact.update_column("email",params[:email])
    end
    respond_to do |format|
      if @camp.update(camp_params)
        format.html { redirect_to edit_camp_path(@camp), notice: 'Camp was successfully updated.' }
        format.json { render :edit, status: :ok, location: @camp }
      else
        format.html { render :edit }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_value
    case params[:value]
      when "bar"
        @camp.bar = params[:change_to] == "true" ? true : false
      when "str"
        @camp.str = params[:change_to] == "true" ? true : false
      when "bsy"
        @camp.bsy = params[:change_to] == "true" ? true : false
      when "member"
        @camp.pccca_member = params[:change_to] == "true" ? true : false
    end
    respond_to do |format|
      if @camp.save
        format.html { render :nothing => true, json: @camp, notice: 'Camp was successfully updated.' }
        format.json { render json: @camp, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /camps/1
  # DELETE /camps/1.json
  def destroy
    @camp.destroy
    respond_to do |format|
      format.html { redirect_to camps_url, notice: 'Camp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camp
      @camp = Camp.friendly.find(params[:id])
    end

    def fix_state
      state = @states.select{|state, abv| state.upcase == params[:state].upcase}
      params[:state] = state.empty? ? params[:state] : state[0][1]
      #byebug
    end

    def states_var
      @states = [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY'],
        ['Alberta', 'AB'],
        ['British Columbia', 'BC'],
        ['Manitoba', 'MB'],
        ['New Brunswick', 'NB'],
        ['Newfoundland', 'NL'],
        ['Nova Scotia','NS'],
        ['Northwest Territories','NT'],
        ['Nunavut','NU'],
        ['Ontario','ON'],
        ['Prince Edward Island','PE'],
        ['Quebec','QC'],
        ['Saskatchewan','SK'],
        ['Yukon','YT']
      ]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def camp_params
      params[:camp][:images_attributes].delete_if{|k,v| v[:image_url].nil?} unless params[:camp][:images_attributes].nil?
      params.require(:camp).permit(:name, :contact_id, :web_url, :pccca_member, :site_setup_id, :camp_desc, :camp_url, :staff_desc, :staff_url,
        images_attributes: [:image_url, :image_type, :camp_id],
        address_attributes: [:address, :address2, :city, :state, :zip, :camp_id],
        site_setup_attributes: [:hotel, :group_local_bath, :group_sep_bath, :rustic, :rv],
        camp_info_attributes: [:description]
      )
    end
end

app/views/camps/all.html.erb
<% content_for :head do %>
  <style>
    body {
      background-color: #eee !important;
    }
  </style>
<%end%>
<div class="container mbm" style="<%='margin-top: 72px' if user_signed_in?%>">
  <div class="row">
    <div class="col-sm-12">
      <h1 class="mtn" style="float: left">Listing Camps</h1>
      <%=link_to "New Camp", new_camp_path, class:"btn btn-default btn-sm left mll mts"%>

      <% @camps.each do |camp| %>
        <div class="row camp-row" style="clear: both">
          <div class="col-sm-4 camp-name">
            <%= camp.name%><br />
          </div>
          <div class="col-sm-2 camp-name">
            <%=label_tag camp.id, "PCCCA Member?", style:"margin-right: 10px"%>
            <%=check_box_tag "#{camp.id}", camp.pccca_member, checked = camp.pccca_member, {class:"pccca_member", data: {value: "member"}}%><br />
          </div>
          <div class="col-sm-3 camp-name">
            <%=label_tag camp.id, "BAR?", style:"margin-right: 3px"%>
            <%=check_box_tag "#{camp.id}", camp.bar, checked = camp.bar, {class:"pccca_member", style:"margin-right: 8px;", data: {value: "bar"}}%>
            <%=label_tag camp.id, "STR?", style:"margin-right: 3px"%>
            <%=check_box_tag "#{camp.id}", camp.str, checked = camp.str, {class:"pccca_member", style:"margin-right: 8px;", data: {value: "str"}}%>
            <%=label_tag camp.id, "BSY?", style:"margin-right: 3px"%>
            <%=check_box_tag "#{camp.id}", camp.bsy, checked = camp.bsy, {class:"pccca_member", style:"margin-right: 8px;", data: {value: "bsy"}}%><br />
          </div>
          <div class="col-sm-3">
            <%= link_to 'Show', camp, :style=>"margin-right: 15px", class:"btn btn-default btn-sm" %>
            <%= link_to 'Edit', edit_camp_path(camp), :style=>"margin-right: 15px", class:"btn btn-default btn-sm"  %>
            <%= link_to 'Destroy', camp, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-default btn-sm"  %>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

<script>
  $(".pccca_member").change(function() {
    var change_to = $(this).is(":checked")
    $.ajax ({
      url: "/camps/"+ $(this).attr("name") + "/update_value",
      method: "PUT",
      data: {"change_to": change_to, "value": $(this).data("value")},
      success:function(data) {
        $(".notice").html("Camp was successfully updated.").show();
        setTimeout(function() {
          $('.notice, .alert').fadeOut();
        }, 3000 );
      }
    });
  });
</script>

app/views/camps/edit.html.erb
<div class="content row" style="<%='margin-top: 72px' if user_signed_in?%>">
  <div class="col-lg-12" style="text-align: left">
    <h1 class="mtn edit-heading" style="float: left; max-width: 90%">Editing - <%=@camp.name%></h1>
    <%= link_to 'Cancel', all_camps_path, class:"btn btn-sm btn-danger mts mll", style:"color: white; float: left" %>
  </div>

  <div class="col-lg-12">
    <%= render 'form' %>
  </div>
</div>

app/views/camps/index-old.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Listing Camps</h1>

      <div class="row">
        <div class="col-sm-12">
          Camp
        </div>
      </div>

      <% @camps.each do |camp| %>
        <div class="row camp-row">
          <div class="col-sm-5">
            <%= camp.name %><br />
          </div>
          <div class="col-sm-3">
            <%= link_to 'Show', camp, :style=>"margin-right: 15px" %>
            <%= link_to 'Edit', edit_camp_path(camp), :style=>"margin-right: 15px" %>
            <%= link_to 'Destroy', camp, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/camps/index.html.erb
<%content_for :head do%>
  <style>
    body {
      background: url('/assets/cover 1.JPG');
      background-size: cover;
    }
  </style>
<%end%>

<div class="row full-width">
  <div class="large-12 columns search top-bar">
    <div class="content">
      <div class="row" style="margin: 0 15px">
        <div class="large-12 columns">
          <%=image_tag 'bar', :class => "float: left"%>
            <p style="float: left;" class="show-desktop">Find a retreat location for your next event for free.  We offer a list of conference and retreat rental locations at Christian camps and conference centers across the United States and Canada.</p>
        </div>
      </div>
    </div>
  </div>
</div><!--end top-bar-->

<div class="row content front-page">
  <p class="show-mobile" style="margin: 0 -15px 10px;">Find a retreat location for your next event for free.  We offer a list of conference and retreat rental locations at Christian camps and conference centers across the United States and Canada.</p>
  <%=form_tag search_camps_path, :id => 'SearchForm', :method => 'get' do %>
    <div class="row">
      <div class="col-lg-6 col-xs-12 form-group" style="padding-left: 0">
        <%=label_tag "city", "City"%><br />
        <%=text_field_tag "city",'', :class => "col-xs-12"%>
      </div>
      <div class="col-lg-6 col-xs-12 form-group" style="padding-left: 0">
        <%=label_tag "state", "State or Province"%><br />
        <%=text_field_tag "state",'',:class => "col-xs-12"%>
      </div>
    </div>

    <div class="row">
      <h2 style="margin-top: 0"><em><strong>Optional Information</strong></em></h2>
      <p>Please enter the number of beds in each lodging accommodation you will require for your retreat:</p>
      <div class="col-lg-6 columns" style="margin-top: 8px">
        <label>Hotel/Motel-style Housing with private bathrooms</label>
      </div>
      <div class="col-lg-2 end">
        <input type="number" class="col-xs-12" name="hotel" min="0" />
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6">
        <label>Group Housing with shared bathrooms in the same building</label>
      </div>
      <div class="col-lg-2 end">
        <input type="number" class="col-xs-12" name="group_local_bath" min="0" />
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6">
        <label>Group Housing with bathroom facilities in a nearby/separate building</label>
      </div>
      <div class="col-lg-2 end">
        <input type="number" class="col-xs-12" name="group_sep_bath" min="0" />
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6">
        <label>Rustic Housing (screened cabins, teepees, platform tents, etc.) with bathroom facilities in a local/separate building</label>
      </div>
      <div class="col-lg-2 end">
        <input type="number" class="col-xs-12" name="rustic" min="0" />
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6">
        <label>RV or Tent Sites (number of sites) with bathroom facilities in a local/separate building</label>
      </div>
      <div class="col-lg-2 end">
        <input type="number" class="col-xs-12" name="rv" min="0" />
      </div>
    </div>
    <input type="submit" value="Search For A Retreat Center" class="submit"/>
  <%end%>
</div>

<div class="credit">
  Laurel Ridge Camp, Conference, and Retreat Center<br/>
  Laurel Springs, NC
</div>

app/views/camps/new.html.erb
<div class="content row" style="<%='margin-top: 72px' if user_signed_in?%>">
  <div class="col-lg-12" style="text-align: left">
    <h1 class="mtn edit-heading" style="float: left; max-width: 90%">New Camp</h1>
    <%= link_to 'Cancel', all_camps_path, class:"btn btn-sm btn-danger mts mll", style:"color: white; float: left" %>
  </div>

  <div class="col-lg-12">
    <%= render 'form' %>
  </div>
</div>

app/views/camps/search.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyDBBGiFgEnyUDYe4V-751ptbtLIgR7dpMU"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

<p id="notice"><%= notice %></p>

<div class="row full-width fixed" style="top: 0; z-index: 10; <%="margin-top: 50px;" if user_signed_in?%>">
  <div class="col-lg-12 top-bar">
    <div class="col-lg-4 col-xs-5 ">
      <%=link_to (image_tag 'bar'), root_path%>
    </div>
    <div class="col-lg-8 col-xs-7 menu">
      <h3><%=link_to '&#8610; Back to Search'.html_safe, root_path%></h3>
    </div>
  </div>
</div><!--end top-bar-->

<div class="container results">
  <div class="row">
    <div class="col-lg-8">
      <%if !(@camps.empty? && @farther_camps.empty?)%>
        <div class="row featured">
          <%camp_plural = @camps.reject{|c| c.pccca_member == false}.count > 1 ? "Center".pluralize : "Center"%>
          <%header = '<h2 class="results-text">Featured ' + camp_plural + '</h2>'%>
          <%=header.html_safe if @camps.reject{|c| c.pccca_member == false}.count > 0%>
          <% @camps.reject{|c| c.pccca_member == false}.each do |camp| %>
            <%image = Image.where("camp_id = ? and image_type = 'bar'", camp.id).blank? ? Image.where("camp_id = ? and image_type = 'pccca'", camp.id) : Image.where("camp_id = ? and image_type = 'bar'", camp.id)%>
            <div class="col-md-6 col-sm-12" style="margin-bottom:30px">
              <%background = image.blank? ? "" : "background-image: url(#{asset_path image.first.image_url(:medium)})"%>
              <div class="card-container <%="no-image" if image.blank?%> location-<%=camp.address.id%>" style="<%=background%>">
                <div class="card-overlay" style="<%='display: none;' if image.blank?%>"></div>
                <%#url = asset_path image.first.image_url if !image.blank?%>
                <%#=image_tag url%>

                <h4 class="name"><%=camp.name%></h4>
                <p class="city"><%=camp.address.city%>, <%=camp.address.state%></p>
                <%= link_to 'Find Out More', camp, :class => "details results ripple-effect", :"data-ripple-color" => "#871084", :"data-ripple-limit" => ".card-container"%>
              </div>
            </div><!-- ending of result -->
          <%end%>
        </div>
        <div class="row">
          <%='<hr style="padding: 15px"/>'.html_safe unless @camps.reject{|c| c.pccca_member == false}.empty?%>
          <% @camps.reject{|c| c.pccca_member == true}.each do |camp| %>
            <%image = Image.where("camp_id = ? and image_type = 'bar'", camp.id).blank? ? Image.where("camp_id = ? and image_type = 'pccca'", camp.id) : Image.where("camp_id = ? and image_type = 'bar'", camp.id)%>
            <div class="col-md-6 col-sm-12" style="margin-bottom:30px">
              <%background = image.blank? ? "" : "background-image: url(#{asset_path image.first.image_url(:medium)})"%>
              <div class="card-container <%="no-image" if image.blank?%> location-<%=camp.address.id%>" style="<%=background%>">
                <div class="card-overlay" style="<%='display: none;' if image.blank?%>"></div>
                <%#url = "site_images/"+image.first.image_url if !image.blank?%>
                <%#=image_tag url%>

                <h4 class="name"><%=camp.name%></h4>
                <p class="city"><%=camp.address.city%>, <%=camp.address.state%></p>
                <%= link_to 'Find Out More', camp, :class => "details results ripple-effect", :"data-ripple-color" => "#871084", :"data-ripple-limit" => ".card-container"%>
              </div>
            </div><!-- ending of result -->
          <%end%>
        </div>
        <%= '<div style="height: 50px"></div>'.html_safe unless @camps.empty?%>
        <div class="row">
          <%if !(@farther_camps.empty?)%>
            <h2 class="results-text">Conference centers just outside your search area</h2>
          <%end%>
          <% @farther_camps.each do |camp| %>
            <%image = Image.where("camp_id = ? and image_type = 'bar'", camp.id).blank? ? Image.where("camp_id = ? and image_type = 'pccca'", camp.id) : Image.where("camp_id = ? and image_type = 'bar'", camp.id)%>
            <div class="col-lg-4 col-md-6 col-sm-12" style="margin-bottom:30px">
              <%background = image.blank? ? "" : "background-image: url(#{asset_path image.first.image_url(:medium)})"%>
              <div class="card-container <%="no-image" if image.blank?%> location-<%=camp.address.id%>" style="<%=background%>">
                <div class="card-overlay" style="<%='display: none;' if image.blank?%>"></div>
                <%#url = image.first.image_url if !image.blank?%>
                <%#=image_tag url%>

                <h4 class="name"><%=camp.name%></h4>
                <p class="city"><%=camp.address.city%>, <%=camp.address.state%></p>
                <%= link_to 'Find Out More', camp, :class => "details results ripple-effect", :"data-ripple-color" => "#871084", :"data-ripple-limit" => ".card-container"%>
              </div>
            </div><!-- ending of result -->
          <%end%>
        </div>
      <%else%>
        <h2 class="results-text">No Conference centers found. Please try searching again.</h2>
        <%=form_tag search_camps_path, :id => 'ReSearchForm', :method => 'get' do %>
          <div class="row">
            <div class="col-lg-6 col-xs-12 form-group" style="padding-left: 0">
              <%=label_tag "city", "City"%><br />
              <%=text_field_tag "city",'', :class => "col-xs-12"%>
            </div>
            <div class="col-lg-6 col-xs-12 form-group" style="padding-left: 0">
              <%=label_tag "state", "State"%><br />
              <%=text_field_tag "state",'',:class => "col-xs-12"%>
            </div>
          </div>

          <div class="row">
            <h2 style="margin-top: 0"><em><strong>Optional Information</strong></em></h2>
            <p>Please enter the number of beds in each lodging accommodation you will require for your retreat:</p>
            <div class="col-lg-6 columns" style="margin-top: 8px">
              <label>Hotel/Motel-style Housing with private bathrooms</label>
            </div>
            <div class="col-lg-2 end">
              <input type="number" class="col-xs-12" name="hotel" min="0" />
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <label>Group Housing with shared bathrooms in the same building</label>
            </div>
            <div class="col-lg-2 end">
              <input type="number" class="col-xs-12" name="group_local_bath" min="0" />
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <label>Group Housing with bathroom facilities in a nearby/separate building</label>
            </div>
            <div class="col-lg-2 end">
              <input type="number" class="col-xs-12" name="group_sep_bath" min="0" />
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <label>Rustic Housing (screened cabins, teepees, platform tents, etc.) with bathroom facilities in a local/separate building</label>
            </div>
            <div class="col-lg-2 end">
              <input type="number" class="col-xs-12" name="rustic" min="0" />
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <label>RV or Tent Sites (number of sites) with bathroom facilities in a local/separate building</label>
            </div>
            <div class="col-lg-2 end">
              <input type="number" class="col-xs-12" name="rv" min="0" />
            </div>
          </div>
          <input type="submit" value="Search For A Retreat Center" class="submit"/>
        <%end%>
      <%end%>
    </div>
    <div class="col-lg-4">
      <div class="affix">
        <div id="map" style='height: 75vh;'></div>
      </div>
    </div>
  </div>
</div>

<br>

<script type="text/javascript">
handler = Gmaps.build('Google', {markers: {clusterer: undefined}});
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);

  _.each(<%=raw @hash.to_json %>, function(json, index){
    json.marker = markers[index];
    $(".location-" + json.id).on('mouseover', function() {
      //handler.getMap().setZoom(9);
      json.marker.setMap(handler.getMap()); //because clusterer removes map property from marker
      //json.marker.panTo();
      google.maps.event.trigger(json.marker.getServiceObject(), 'click');
    });
    $(".location-" + json.id).on('mouseout', function() {
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      json.marker.infowindow.close()
    });
  });

  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  <%if @hash.size == 1 && @hash.first[:id] == 0%>
    handler.getMap().setZoom(5);
  <%end%>
});
</script>

<%#= link_to 'New Camp', new_camp_path %>