config/routes.rb
Rails.application.routes.draw do
  #devise_scope :user do
  #  get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  #  get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  #end
  devise_for :users
  resources :camp_types
  resources :camp_infos
  resources :amenities
  resources :site_setups
  resources :images
  resources :contacts
  resources :addresses
  resources :camps do
    collection do
      get 'search'
      get 'all'
      get 'site_index'
    end
    member do
      put 'update_value'
    end
  end

  get '*path' => redirect('/')

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

  # The priority is based on order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'camps#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/site_setup.rb
class SiteSetup < ActiveRecord::Base
  belongs_to :camp

  def housing_exists
    hotel.to_i > 0 || group_local_bath.to_i > 0 || group_sep_bath.to_i > 0 || rustic.to_i > 0 || rv.to_i > 0
  end
end

app/controllers/site_setups_controller.rb
class SiteSetupsController < ApplicationController
  before_action :set_site_setup, only: [:show, :edit, :update, :destroy]

  # GET /site_setups
  # GET /site_setups.json
  def index
    @site_setups = SiteSetup.all
  end

  # GET /site_setups/1
  # GET /site_setups/1.json
  def show
  end

  # GET /site_setups/new
  def new
    @site_setup = SiteSetup.new
  end

  # GET /site_setups/1/edit
  def edit
  end

  # POST /site_setups
  # POST /site_setups.json
  def create
    @site_setup = SiteSetup.new(site_setup_params)

    respond_to do |format|
      if @site_setup.save
        format.html { redirect_to @site_setup, notice: 'Site setup was successfully created.' }
        format.json { render :show, status: :created, location: @site_setup }
      else
        format.html { render :new }
        format.json { render json: @site_setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_setups/1
  # PATCH/PUT /site_setups/1.json
  def update
    respond_to do |format|
      if @site_setup.update(site_setup_params)
        format.html { redirect_to @site_setup, notice: 'Site setup was successfully updated.' }
        format.json { render :show, status: :ok, location: @site_setup }
      else
        format.html { render :edit }
        format.json { render json: @site_setup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_setups/1
  # DELETE /site_setups/1.json
  def destroy
    @site_setup.destroy
    respond_to do |format|
      format.html { redirect_to site_setups_url, notice: 'Site setup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_setup
      @site_setup = SiteSetup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_setup_params
      params.require(:site_setup).permit(:hotel, :group_local_bath, :group_sep_bath, :rustic, :rv)
    end
end

app/views/site_setups/_form.html.erb
<%= form_for(@site_setup) do |f| %>
  <% if @site_setup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site_setup.errors.count, "error") %> prohibited this site_setup from being saved:</h2>

      <ul>
      <% @site_setup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hotel %><br>
    <%= f.number_field :hotel %>
  </div>
  <div class="field">
    <%= f.label :group_local_bath %><br>
    <%= f.number_field :group_local_bath %>
  </div>
  <div class="field">
    <%= f.label :group_sep_bath %><br>
    <%= f.number_field :group_sep_bath %>
  </div>
  <div class="field">
    <%= f.label :rustic %><br>
    <%= f.number_field :rustic %>
  </div>
  <div class="field">
    <%= f.label :rv %><br>
    <%= f.number_field :rv %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/site_setups/edit.html.erb
<h1>Editing Site Setup</h1>

<%= render 'form' %>

<%= link_to 'Show', @site_setup %> |
<%= link_to 'Back', site_setups_path %>

app/views/site_setups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Site Setups</h1>

<table>
  <thead>
    <tr>
      <th>Hotel</th>
      <th>Group local bath</th>
      <th>Group sep bath</th>
      <th>Rustic</th>
      <th>Rv</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @site_setups.each do |site_setup| %>
      <tr>
        <td><%= site_setup.hotel %></td>
        <td><%= site_setup.group_local_bath %></td>
        <td><%= site_setup.group_sep_bath %></td>
        <td><%= site_setup.rustic %></td>
        <td><%= site_setup.rv %></td>
        <td><%= link_to 'Show', site_setup %></td>
        <td><%= link_to 'Edit', edit_site_setup_path(site_setup) %></td>
        <td><%= link_to 'Destroy', site_setup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site setup', new_site_setup_path %>

app/views/site_setups/new.html.erb
<h1>New Site Setup</h1>

<%= render 'form' %>

<%= link_to 'Back', site_setups_path %>

app/views/site_setups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hotel:</strong>
  <%= @site_setup.hotel %>
</p>

<p>
  <strong>Group local bath:</strong>
  <%= @site_setup.group_local_bath %>
</p>

<p>
  <strong>Group sep bath:</strong>
  <%= @site_setup.group_sep_bath %>
</p>

<p>
  <strong>Rustic:</strong>
  <%= @site_setup.rustic %>
</p>

<p>
  <strong>Rv:</strong>
  <%= @site_setup.rv %>
</p>

<%= link_to 'Edit', edit_site_setup_path(@site_setup) %> |
<%= link_to 'Back', site_setups_path %>