config/routes.rb
Rails.application.routes.draw do
  #devise_scope :user do
  #  get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  #  get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  #end
  devise_for :users
  resources :camp_types
  resources :camp_infos
  resources :amenities
  resources :site_setups
  resources :images
  resources :contacts
  resources :addresses
  resources :camps do
    collection do
      get 'search'
      get 'all'
      get 'site_index'
    end
    member do
      put 'update_value'
    end
  end

  get '*path' => redirect('/')

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

  # The priority is based on order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'camps#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/camp_info.rb
class CampInfo < ActiveRecord::Base
  has_and_belongs_to_many :amenities
  belongs_to :camp
end

app/controllers/camp_infos_controller.rb
class CampInfosController < ApplicationController
  before_action :set_camp_info, only: [:show, :edit, :update, :destroy]

  # GET /camp_infos
  # GET /camp_infos.json
  def index
    @camp_infos = CampInfo.all
  end

  # GET /camp_infos/1
  # GET /camp_infos/1.json
  def show
  end

  # GET /camp_infos/new
  def new
    @camp_info = CampInfo.new
  end

  # GET /camp_infos/1/edit
  def edit
  end

  # POST /camp_infos
  # POST /camp_infos.json
  def create
    @camp_info = CampInfo.new(camp_info_params)

    respond_to do |format|
      if @camp_info.save
        format.html { redirect_to @camp_info, notice: 'Camp info was successfully created.' }
        format.json { render :show, status: :created, location: @camp_info }
      else
        format.html { render :new }
        format.json { render json: @camp_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /camp_infos/1
  # PATCH/PUT /camp_infos/1.json
  def update
    respond_to do |format|
      if @camp_info.update(camp_info_params)
        format.html { redirect_to @camp_info, notice: 'Camp info was successfully updated.' }
        format.json { render :show, status: :ok, location: @camp_info }
      else
        format.html { render :edit }
        format.json { render json: @camp_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /camp_infos/1
  # DELETE /camp_infos/1.json
  def destroy
    @camp_info.destroy
    respond_to do |format|
      format.html { redirect_to camp_infos_url, notice: 'Camp info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camp_info
      @camp_info = CampInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def camp_info_params
      params.require(:camp_info).permit(:type_id, :description, :url, :camp_id)
    end
end

app/views/camp_infos/_form.html.erb
<%= form_for(@camp_info) do |f| %>
  <% if @camp_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@camp_info.errors.count, "error") %> prohibited this camp_info from being saved:</h2>

      <ul>
      <% @camp_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_id %><br>
    <%= f.number_field :type_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :camp_id %><br>
    <%= f.number_field :camp_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/camp_infos/edit.html.erb
<h1>Editing Camp Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @camp_info %> |
<%= link_to 'Back', camp_infos_path %>

app/views/camp_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Camp Infos</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Description</th>
      <th>Url</th>
      <th>Camp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @camp_infos.each do |camp_info| %>
      <tr>
        <td><%= camp_info.type_id %></td>
        <td><%= camp_info.description %></td>
        <td><%= camp_info.url %></td>
        <td><%= camp_info.camp_id %></td>
        <td><%= link_to 'Show', camp_info %></td>
        <td><%= link_to 'Edit', edit_camp_info_path(camp_info) %></td>
        <td><%= link_to 'Destroy', camp_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Camp info', new_camp_info_path %>

app/views/camp_infos/new.html.erb
<h1>New Camp Info</h1>

<%= render 'form' %>

<%= link_to 'Back', camp_infos_path %>

app/views/camp_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @camp_info.type_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @camp_info.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @camp_info.url %>
</p>

<p>
  <strong>Camp:</strong>
  <%= @camp_info.camp_id %>
</p>

<%= link_to 'Edit', edit_camp_info_path(@camp_info) %> |
<%= link_to 'Back', camp_infos_path %>