config/routes.rb
Rails.application.routes.draw do
  #devise_scope :user do
  #  get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  #  get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  #end
  devise_for :users
  resources :camp_types
  resources :camp_infos
  resources :amenities
  resources :site_setups
  resources :images
  resources :contacts
  resources :addresses
  resources :camps do
    collection do
      get 'search'
      get 'all'
      get 'site_index'
    end
    member do
      put 'update_value'
    end
  end

  get '*path' => redirect('/')

  get 'sitemap.xml', :to => 'sitemap#index', :defaults => { :format => 'xml' }

  # The priority is based on order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'camps#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_admin_nav.html.erb
<div class="nav-bar">
  <div class="container">
    <div class="row admin-nav">
      <div class="col-lg-9">
        <%=image_tag "bar.png", height: "50px"%>
        &nbsp;&nbsp;&nbsp;&nbsp;Logged in as <%=current_user.email%>
      </div>
      <div class="col-lg-3 sign-out">
        <%=link_to "All Camps", camps_path%>
        <%=link_to "Search Page", search_camps_path%>
        <%=link_to "Sign Out", destroy_user_session_path, :method => "delete"%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_user_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">
          <%=image_tag "bar", style:"max-height: 45px;margin-top: -12px;"%>
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <%camp = (Contact.find_by_email current_user.email).camp%>
          <li><%=link_to "Edit Your Camp", edit_camp_path(camp)%></li>
          <li><%=link_to "View Your Camp", camp_path(camp)%></li>
          <li><%=link_to "Sign Out", destroy_user_session_path, :method => "delete"%></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Book A Retreat.com - Rent a Retreat Location or Conference Center</title>
  <%= stylesheet_link_tag 'application', 'app', 'style', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= yield :head %>
</head>
<body>

<%if user_signed_in?%>
  <%if current_user.try(:admin?)%>
    <%=render "layouts/admin_nav"%>
  <%else%>
    <%=render "layouts/user_nav"%>
  <%end%>
<%end%>

<p class="notice btn-success" style="display: <%=!!notice ? "block" : "none"%>"><%= notice %></p>
<p class="alert btn-warning" style="display: <%=!!alert ? "block" : "none"%>"><%= alert %></p>

<%= yield %>


</body>
</html>